name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v4
        with:
          pr-comment: 'Thank you for contributing to Graphs by opening this pull request. The repository has been moved to the GNOME Gitlab, please open a merge request at [the GitLab page](https://gitlab.gnome.org/World/Graphs/-/merge_requests) instead.'
